{ok, Cwd} = file:get_cwd(),
io:format("~p~n", [Cwd]),
{ok, List} = file:list_dir(filename:join(filename:dirname(SCRIPT), "lib")),
io:format("~p~n", [List]),
[
    {deps, [{list_to_atom(D), {local, Cwd ++ "/lib/" ++ D}} || D <- List, filelib:is_dir("lib/" ++ D)]},
    {plugins, [
        {rebar_subdir_plugin, {git, "https://github.com/sjanota/rebar_subdir_plugin.git", {branch, "master"}}}
    ]}
].